andela/AndelaEatsApi

.env.sample

Added .env.sample file.
To use, create a new file `.env` copy contents of `.env.sample` to `.env` and fill as your environment requires.

added env sample

---

chow.py
requirements.txt
run.py

Added ability to see all routes registered within the application.
Added some cosmetic surgery to the chow.py file.

Ch show routes cli

---

README.md
tests/integration/endpoints/test_vendor_endpoints.py

Ch edit readme

---

app/blueprints/meal_blueprint.py
tests/integration/endpoints/test_meal_items_endpoint.py

chore(meal): Add validator decorators

---

app/blueprints/menu_blueprint.py
app/utils/security.py
tests/integration/endpoints/test_menu_endpoints.py

- Includes validations for menu's `request.body` on create menu and update menu
- Add the validations to the endpoints
- Add tests for the task
- Run `pytest`
N/A
>- [#160928484](https://www.pivotaltracker.com/story/show/160928484)

#160928484 Menu Validation

---

app/utils/auth.py

- fixes a bug in the `has_permission` decorator function function
- Track the bug
- Fix the bug
- Clone the branch `bg-fix-has-permission`
- Start the application
- Add multiple instances of the `user_role` class. They should all enjoy all the assigned permissions
N/A
N/A
￼
N/A

fix bug in has-permission function

---

.circleci/config.yml
Procfile

add python command to procfile

---

app/utils/auth.py
run.py

add options to handle preflight

---

app/utils/auth.py
run.py

remove after request add option check

---

app/blueprints/menu_blueprint.py
app/controllers/menu_controller.py
app/controllers/vendor_engagement_controller.py
app/repositories/menu_repo.py
tests/integration/endpoints/test_menu_endpoints.py

• Enable user to delete their own orders
• Include the endpoint to get menu by date range
• Update endpoint to get menu by a date to pull data like create menu
• Create skeletal test to be updated
• Clone the branch `fx-menu-post-list-data`
• Checkout to the branch
• Run `flask db upgrade`

clean up controllers, update admin menu + add d menu range

---

app/controllers/menu_controller.py

multiple values for side items and proteins

---

app/blueprints/documentation/create_engagement.yml
app/blueprints/documentation/delete_engagement.yml
app/blueprints/documentation/get_all_upcoming_vendor_engagement.yml
app/blueprints/documentation/get_all_vendor_engagements.yml
app/blueprints/documentation/get_vendor_engagement_by_id.yml
app/blueprints/documentation/update_engagement.yml
app/blueprints/documentation/update_menu.yml
app/blueprints/documentation/update_order.yml
app/blueprints/vendor_engagement_blueprint.py

more documentation: added vendor engagement

---

app/blueprints/documentation/create_menu.yml
app/controllers/menu_controller.py

fix bug of pulling sub menu items correctly

fix bug of pulling sub items

---

app/controllers/menu_controller.py
app/models/menu.py
tests/integration/endpoints/test_menu_endpoints.py

- change the type of `Menu` date column to type `date`
- update the Menu controller to prevent duplication of main meal id
- Fix failing tests
- add extra test

prevent multiple menus with same main meal id for the same day

---

app/blueprints/base_blueprint.py
app/blueprints/bot_blueprint.py
app/controllers/base_controller.py
app/controllers/bot_controller.py
app/utils/__init__.py
app/utils/auth.py
app/utils/slackhelper.py

* Updated bot_blueprint to accept GET or POST parameters.
* Added post_params and get_params methods to base controller. This will return a list of values within the POST body and query strings respectively.
* Implemented the logic for the bot returning the dates menu.
* Added date range method to utils.
* Exempted `/bot` endpoints from auth and location header checks.
* Created a slack helper file for interacting with slack API.

* Registered Bot Controller on the base controller

---

app/controllers/order_controller.py
factories/order_factory.py
tests/integration/endpoints/test_orders_endpoints.py

* changed default orders get to list orders for the day after

* changed default orders get to list orders for the day after

---

app/__init__.py
app/controllers/bot_controller.py

- Add Slack features requested by the Product Owners.
- Slack users are able to view all the menu without ordering.
- Slack users are able to rate meals.
- Slack users are able to navigate to the previous view.
run the slash command `/aetest` from Slack and attempt to book or rate a menu. You will be able to rate or book a meal and navigate backwards
None

Add requested features to the Slack integration

---

app/repositories/activity_repo.py
tests/unit/repositories/test_activity_repo.py
tests/unit/repositories/test_base_repo.py
tests/unit/repositories/test_location_repo.py
tests/unit/repositories/test_order_repo.py
tests/unit/repositories/test_user_role_repo.py
tests/unit/repositories/test_vendor_rating_repo.py

- write tests for all uncovered lines in the repository folder
- write tests for all uncovered lines in the repository folder
- pytest --cov=app/repositories/
- None
- [163817748](https://www.pivotaltracker.com/story/show/163817748)

#163817748 Write tests for repositories

---

app/controllers/bot_controller.py
app/controllers/location_controller.py
app/controllers/role_controller.py
app/controllers/vendor_rating_controller.py
tests/base_test_case.py
tests/integration/endpoints/test_bot_endpoints.py
tests/integration/endpoints/test_location_endpoints.py
tests/integration/endpoints/test_menu_endpoints.py
tests/integration/endpoints/test_orders_endpoints.py
tests/integration/endpoints/test_role_endpoints.py
tests/integration/endpoints/test_vendor_engagement_endpoints.py
tests/integration/endpoints/test_vendor_rating_endpoints.py
tests/integration/endpoints/user_role.py
tests/unit/controllers/test_location_controller.py
tests/unit/controllers/test_role_controller.py

* write tests for all uncovered lines in the blueprints folder except the `bot_blueprint.py` file
* write tests for all uncovered lines in the blueprints folder except the `bot_blueprint.py` file
* pytest --cov=app/blueprints/
* None
* [163859255](https://www.pivotaltracker.com/story/show/163859255)

#163859255 Write tests for blueprints 

---

app/controllers/__init__.py
app/controllers/bot_controller.py
tests/integration/endpoints/test_bot_endpoints.py
tests/mock.py
tests/unit/test_utils.py

- write tests for bot controller module
- add tests for the `bot` function
- add tests for `get_menu_start_end_on`
- run `pytest`
None

Add bot controller tests

---

app/controllers/__init__.py
app/controllers/user_controller.py

- Removes the user_controller.py module.
- user_controller.py is removed from the repo because it is doing nothing right now.
- N/A
- user_controller.py was deleted on approval from @Maxcutex since it was doing nothing and bringing the code coverage score down.
- [163858988](https://www.pivotaltracker.com/story/show/163858988)

Removing user_controller module since it is doing nothing.

---

tests/unit/models/test_base_model.py

* write tests for all uncovered lines in the `base_model.py` file
* write tests for all uncovered lines in the `base_model.py` file
* pytest --cov=app/models/
* None
* [163859343](https://www.pivotaltracker.com/story/show/163859343)

#163859343 Write tests for base model

---

app/controllers/user_controller.py
tests/unit/controllers/test_user_controller.py

- List the admin users.
- Adds user_controller.py with list_admin_users
- Test the user_controller.py list_admin_users
Run the command pytest --cov=app.controllers.user_controller tests/unit/controllers/test_user_controller.py
- Admin users need to be viewed and listed.

Listing admin users

---

Procfile

add seed database to master

---

app/blueprints/base_blueprint.py
app/blueprints/documentation/get_all_admin_users.yml
app/blueprints/user_blueprint.py
tests/integration/endpoints/test_user_endpoints.py

- Creates a user blueprint for on the endpoint `/api/v1/users/admin`
- Create user blueprint
- Add tests for blueprint
- Refactor any other failing tests
- Document endpoint `/users/admin`
- Pull this branch locally by running `git fetch ft-users-blue-print-164040572`
- Run `pytest`
- Previously the endpoint `api/v1/users/admin` did not exist. This endpoint now exists and can be able to return a list of admin users
- [#164040572](https://www.pivotaltracker.com/story/show/164040572)

#164014105 - Create user blue print

---

app/controllers/order_controller.py
app/models/base_model.py
app/repositories/base_repo.py
tests/unit/repositories/test_user_role_repo.py

* update the `orderController` to include `meal_type` and `user_rating`
* update the `orderController` to include `meal_type` and `user_rating`
* Pull and checkout to this branch locally by running `git fetch origin ch-order-include-meal-type-164239199 && git checkout ch-order-include-meal-type-164239199`
* Start the application using `flask run`
* Get all orders by a specific user. The response should include the `meal_type` and `user_rating`
* N/A.
* [164239199](https://www.pivotaltracker.com/story/show/164239199) 
[Maintains #164239199]

#164239199 update the orderController to include meal_type and user_rating

---

README.md

* update the readme to include the setup process
* update the readme to include the setup process
* N/A
* N/A.
* [164362236](https://www.pivotaltracker.com/story/show/164362236)

#164362236 update the readme to include the setup process

---

app/blueprints/order_blueprint.py
app/controllers/base_controller.py
app/controllers/order_controller.py
tests/unit/controllers/test_order_controller.py

* fix update order bug that prevents updating the order with a different menu item
* fix update order bug that prevents updating the order with a different menu item
* N/A
* N/A.
* [164392016](https://www.pivotaltracker.com/story/show/164392016)

#164392016 fix update order bug

---

app/blueprints/base_blueprint.py
app/blueprints/documentation/get_report.yml
app/blueprints/reports_blueprint.py
app/blueprints/role_blueprint.py
app/controllers/__init__.py
app/controllers/reports_controller.py
app/repositories/vendor_engagement_repo.py
app/repositories/vendor_rating_repo.py
requirements.txt
tests/integration/endpoints/test_reports_endpoint.py
tests/integration/endpoints/test_vendor_rating_endpoints.py
tests/unit/repositories/test_vendor_rating_repo.py

* Creates the endpoint for dashboard report
* add the endpoint that returns the rating and order information for a given period, default of 14 days
* Add documentation for the endpoint
* pull the branch `generate-dashboard-reporting` and checkout to the branch
* send  `get` request to `localhost:5000/api/v1/reports/` 
You will get the report for the past 14 days, by default. To customize the number of days, add the `?period=x` to the url, where`x` is the number of days.
[158863653](https://www.pivotaltracker.com/story/show/158863653)

Generate dashboard reporting

---

requirements.txt

* Remove extraneous requirements from from `requirements.txt` 
* delete `django` and `pillow` as requirements
* pull the branch `update-requirements-txt` and checkout to the branch
* open the requirements.txt file. You will find that django and pillow are no longer there

Remove extraneous packages from requirments.txt

---

app/blueprints/documentation/disable_user_roles.yml
app/blueprints/role_blueprint.py
app/controllers/role_controller.py
tests/integration/endpoints/test_role_endpoints.py
tests/unit/controllers/test_role_controller.py

* Fix the endpoint to disable user-role
* Update the `role_blueprint` to use `userId` and `roleId`
* refactor the `role_controller` to user `userId` and `roleId` to disable user-role
* fix failing tests
* pull the branch `fix-user-role-disable` and checkout to the branch
* send a post request to `localhost:5000/api/v1/roles/user/disable/`, containing data for userId and roleId in the body. If you have the appropriate permission, you will receive a success response. 
[164480954](https://www.pivotaltracker.com/story/show/164480954)
**Sample screenshot**

fix the endpoint to disable user-role

---

app/blueprints/documentation/update_faq.yml
app/blueprints/faq_blueprint.py
app/controllers/base_controller.py
app/controllers/faq_controller.py
tests/integration/endpoints/test_faq_enpoints.py
tests/unit/controllers/test_base_controller.py
tests/unit/controllers/test_faq_controller.py

* create the FAQ update endpoint
* create the FAQ update endpoint
* Pull and checkout to this branch locally by running `git fetch origin ft-update-faqs-164400743 && git checkout ft-update-faqs-164400743`
* Start the application using `flask run`
* To create FAQ, hit the endpoint `UPDATE {{base-url}}/api/v1/faqs/faq_id`.
* N/A.
* [164400743](https://www.pivotaltracker.com/story/show/164400743)

#164400743 update FAQ endpoint

---

app/blueprints/documentation/delete_faq.yml
app/blueprints/faq_blueprint.py
app/controllers/faq_controller.py
tests/integration/endpoints/test_faq_enpoints.py
tests/unit/controllers/test_faq_controller.py

* create the FAQ delete endpoint
* create the FAQ delete endpoint
* Pull and checkout to this branch locally by running `git fetch origin ft-delete-faqs-164400702 && git checkout ft-delete-faqs-164400702`
* Start the application using `flask run`
* To create FAQ, hit the endpoint `DELETE {{base-url}}/api/v1/faqs/`.
* N/A.
* [164400702](https://www.pivotaltracker.com/story/show/164400702)

#164400702 delete FAQ endpoint

---

migrations/versions/4a83f38b751e_.py

Fix head issues

---

migrations/versions/cfeef5d4b2cd_.py

Fix vendor default

---

migrations/versions/cfeef5d4b2cd_.py

Fix vendor set nullable true

---

app/blueprints/base_blueprint.py
app/blueprints/documentation/create_meal_session.yml
app/blueprints/meal_session_blueprint.py
app/controllers/meal_session_controller.py
app/repositories/__init__.py
app/repositories/base_repo.py
app/repositories/meal_session_repo.py
app/utils/security.py
factories/__init__.py
tests/integration/endpoints/test_meal_session_endpoints.py
tests/unit/controllers/test_meal_session_controller.py
tests/unit/repositories/test_meal_session_repo.py

* Creates endpoint to add meal sessions
* Create the Meal session blueprint
* Create the Meal session controller
* Modify the Meal session repo
* Add tests 
* Pull and checkout to this branch locally by running `git fetch origin ft-create-a-meal-session-164679962 && git checkout ft-create-a-meal-session-164679962`
* Start the application.
* Navigate the swagger documentations in the `Meal Sessions` section to view how to use the endpoint
* Try to create meal sessions
* N/A.
* [164679962](https://www.pivotaltracker.com/story/show/164679962)

#164679962 - Create a meal session endpoint

---

app/blueprints/documentation/update_meal_session.yml
app/blueprints/meal_session_blueprint.py
app/controllers/meal_session_controller.py
app/repositories/meal_session_repo.py
tests/integration/endpoints/test_meal_session_endpoints.py

* Creates endpoint to update meal sessions
* Update the Meal session blueprint to have update meal session function
* Modify the meal session controller to have an update method
* Modify the Meal session repo to have class methods for validation
* Add tests 
* Pull and checkout to this branch locally by running `git fetch origin ft-update-meal-session-164679965 && git checkout ft-update-meal-session-164679965`
* Start the application.
* Navigate the swagger documentation in the `Meal Sessions` section to view how to use the endpoint
* Try to create meal sessions
* N/A.
* …

#164679965 - An endpoint to update a meal session

---

app/blueprints/documentation/get_user.yml
app/blueprints/user_blueprint.py
app/controllers/user_controller.py
tests/integration/endpoints/test_user_endpoints.py
tests/unit/controllers/test_user_controller.py

* Add endpoint to retrieve a user
* add the endpoint to enable authorized user retrieve a given user
* add tests
* Pull and checkout to this branch locally by running `git fetch origin ft-retrieve-user-164679949 && git ft-retrieve-user-164679949`
* start the server `flask run`
* Hit the endpoint `GET {{base-url}}/users/slack_id/` to create a retrieve user
N/A
[164679949](https://www.pivotaltracker.com/story/show/164679949)

#164679949 retrieve a user 

---

app/blueprints/documentation/get_meal_sessions.yml
app/blueprints/meal_session_blueprint.py
app/controllers/meal_session_controller.py
app/models/base_model.py
factories/location_factory.py
tests/integration/endpoints/test_meal_session_endpoints.py
tests/integration/endpoints/test_permission_endpoints.py
tests/integration/endpoints/test_role_endpoints.py

* Creates the endpoint to list meal sessions
* add the controller method that returns filtered meal sessions
* Add documentation for the endpoint
* Write the test for the functionality
* pull the branch `16479966-list-meal-sessions` and checkout to the branch
* send  `get` request to `localhost:5000/api/v1/meals/session` You will get a paginated list of meal sessions 
N/A
[16479966](https://www.pivotaltracker.com/story/show/164679966)

#164679966 List meal sessions

---

app/blueprints/documentation/delete_meal_session.yml
app/blueprints/meal_session_blueprint.py
app/controllers/meal_session_controller.py
factories/meal_session_factory.py
tests/integration/endpoints/test_meal_session_endpoints.py
tests/integration/endpoints/test_permission_endpoints.py

* Creates endpoint to delete meal sessions
* Update the Meal session blueprint to have delete meal session function
* Modify the meal session controller to have a delete_meal_session method
* Add tests 
* Pull and checkout to this branch locally by running `git fetch origin ft-delete-meal-session-164679967 && git checkout ft-delete-meal-session-164679967`
* Start the application.
* Navigate the swagger documentation in the `Meal Sessions` section to view how to use the endpoint
* Try to create and delete meal session
* N/A.
* [164679967](https://www.pivotaltracker.com/story/show/16467996 …

#164679967 - An endpoint to delete a meal session

---

app/blueprints/documentation/update_user.yml
app/blueprints/user_blueprint.py
app/controllers/user_controller.py
app/repositories/base_repo.py
tests/integration/endpoints/test_user_endpoints.py
tests/unit/repositories/test_base_repo.py

* Add endpoint to update a user
* To the blueprint and controller add methods to update a user
* To the base repo, add a method to perform a specific search
* Add tests for the functionality added
* Add documentation for the endpoint
* Pull and checkout to this branch locally by running `git fetch origin ft-update-user-164679950 && git ft-update-user-164679950`
* Browse through the documentation by accessing the `api-docs` section on Users to get a feel on how to update a user
* Create a new user and try to update the same user using postman
N/A …

#164679950 - An endpoint to update a user

---

config/__init__.py
config/env.py
tests/base_test_case.py

* fix toggling of APP_ENV between "development" and "testing"
* fix toggling of APP_ENV between "development" and "testing"
* Pull and checkout to this branch locally by running `git fetch origin ch-fix-toggling-app_env-164593680 && ch-fix-toggling-app_env-164593680`
* With `APP_ENV` set to `development` in the `.env` file, run the tests using `pytest`. This should be successful
* The current state of the application requires toggling of `APP_ENV` between `development` and `testing` to run the application in development and testing modes respectively …

#164593680 fix toggling of APP_ENV

---

app/controllers/reports_controller.py

- Adds fix for edge cases, for reports endpoint.
- Add fix for edge cases, when there is no data for `vendors, vendor_engagements` and `orders`, then return an empty list for such cases.
- Checks if there are orders, vendor and engagements before generating payload.
- Fetch and checkout to this branch locally by running git fetch origin bg-fix-edge-cases-reports-165287175 && git checkout bg-fix-edge-cases-reports-165287175
[Pivotal tracker story](https://www.pivotaltracker.com/n/projects/2178749/stories/165287175)
[Finishes #165287175]

#165287175 Fix edge cases on the reports endpoint

---

requirements.txt

* Add pre-commit linting support
* Add pre-commit linting support
* Pull and checkout to this branch locally by running `git fetch origin ch-setup-pre-commit-hook-160251052 && ch-setup-pre-commit-hook-160251052`
* Install requirements `pip install -r requirements.txt`
* The pre-commit hook is set!
* N/A
* [160251052](https://www.pivotaltracker.com/story/show/160251052)

#160251052 Add pre-commit linting support

---

app/controllers/order_controller.py
app/models/__init__.py
tests/integration/endpoints/test_orders_endpoints.py
tests/unit/controllers/test_order_controller.py

* Add logging and exception handling to orders endpoints
* Add functionality to log activities on `Order` model
* refactor order endpoints to handle exceptions
* Fix failing tests
* pull the branch `165184522-order-logging` and checkout to the branch
*add an order to the database. change the user id to a non-existing user and use postman to fetch the order. Rather than throwing an error and you get the order with the user set to null
N/A
[165184522](https://www.pivotaltracker.com/story/show/165184522)

#165184522 Add logging and exception handling to orders endpoints

---

requirements.txt
tests/unit/utils/test_seeders.py

*Disable pre-commit hook
* disable pre-commit hook
* fix failing tests
N/A

Disable pre-commit hook

---

app/blueprints/documentation/get_all_admin_users.yml
app/controllers/user_controller.py
tests/integration/endpoints/test_user_endpoints.py

- Updates the users/admin endpoint
- Update the payload by renaming the keys for roles, from id to role_id and role_name for the role name.
- Fetch and checkout to this branch locally by running `git fetch origin ft-update-user-admin-endpoint-164490677 && git checkout ft-update-user-admin-endpoint-164490677`
N/A
[164490677](https://www.pivotaltracker.com/n/projects/2178749/stories/164490677)

#164490677 Update users/admin endpoint

---

app/controllers/meal_session_controller.py
app/controllers/order_controller.py
app/repositories/base_repo.py
app/repositories/meal_session_repo.py
app/repositories/vendor_rating_repo.py
app/utils/location_time.py
tests/unit/repositories/test_base_repo.py

* Refactor the base repo
* Move the `get_rating` method into the rating_repo module
* move the get_local_time_zone into a stand-alone module
* fix the modules affected by the refactoring
* pull the branch `refactor the base repo` and checkout to the branch
* run `pytest` to confirm the refactor does not break the code
N/A

Refactor the base repo

---

requirements-dev.txt

* Separate development requirements from production requirements
* Separate development requirements from production requirements
* Pull and checkout to this branch locally by running `git fetch origin ch-seperate-requirements-165558573 && git checkout ch-seperate-requirements-165558573`
[165558573](https://www.pivotaltracker.com/story/show/165558573)

#165558573 separate develop requirements

---

.circleci/config.yml
tests/integration/endpoints/test_orders_endpoints.py

* fix failing CircleCI tests
* Update user model and controller to cater for user_type column
* The build checks on this PR must pass.
[165744345](https://www.pivotaltracker.com/story/show/165744345)

#165744345 fix failing CircleCI tests

---

app/repositories/base_repo.py
app/services/andela.py
app/utils/security.py
tests/__init__.py
tests/integration/endpoints/test_role_endpoints.py

* Fix updating of meal-item
* Fix updating of meal-item
* Pull and checkout to this branch locally by running `git fetch origin bg-updating-meal-item-166054380 && bg-updating-meal-item-166054380`
* N/A
* [166054380](https://www.pivotaltracker.com/story/show/166054380)

#166054380 fix updating of meal-item

---

app/blueprints/role_blueprint.py
app/controllers/role_controller.py
app/services/andela.py
app/utils/security.py
tests/integration/endpoints/test_role_endpoints.py
tests/unit/services/test_andela_service.py

* fix user role creation
* fix user role creation
* Pull and checkout to this branch locally by running `git fetch origin bg-user-role-creation-166078621 && bg-user-role-creation-166078621`
* N/A
* [166078621](https://www.pivotaltracker.com/story/show/166078621)

#166078621 fix user role creation

---

app/__init__.py

- Fix trailing slashes error on loading the documentation URL
- Fix trailing slashes error on loading the documentation URL
- Pull and checkout to this branch locally by running `git fetch origin bg-fix-trailing-slashes-166112845 && bg-fix-trailing-slashes-166112845`
- Run the server and go to the URL `http://localhost:5000/apidocs` 
- N/A
- [#166112845](https://www.pivotaltracker.com/story/show/166112845)

#166112845 Fix URL trailing slashes

---

app/controllers/user_controller.py
app/repositories/base_repo.py
app/utils/handled_exceptions.py
run.py
tests/unit/repositories/test_base_repo.py

* Fix get all users endpoint not to return deleted users
* Fix get all users endpoint not to return deleted users
* Pull and checkout to this branch locally by running `git fetch origin bg-get-users-166117453 && bg-get-users-166117453`
* N/A
* [166117453](https://www.pivotaltracker.com/story/show/166117453)

#166117453: fix get all users endpoint not to return deleted users

---

run.py

* Handles individual error exceptions
* Handles individual error exceptions and returns a suitable error message
* Pull and checkout to this branch locally by running `git fetch origin bg-handle-individual-exceptions-166183046`
* Start  the virtual environment `. venv/bin/activate`
* run server `flask run`
* In postman, hit an invalid enpoint like `{{base-url}}/jffnmvkc`
* N/A
* [166183046](https://www.pivotaltracker.com/n/projects/2178749)

#166183046 handle individual exceptions

---

app/controllers/role_controller.py

- fix adding of permissions
- fix adding of permissions
- Pull and checkout to this branch locally by running `git fetch origin bg-fix-add-permissions-166112845 && git checkout bg-fix-add-permissions-166112845`
- Run the server and go to the URL `http://localhost:5000/api/v1/roles/permissions` to create a new permission 
- N/A
- [#166112845](https://www.pivotaltracker.com/story/show/166112845)

 #166112845 Fix adding of permissions

---

app/__init__.py

* Update bugsnag configurations to include the release stage information
* Update bugsnag configurations to include the release stage information
* Pull and checkout to this branch locally by running `git fetch origin ch-update-bugsnag-config-166218729 && ch-update-bugsnag-config-166218729`
* N/A
* [166218729](https://www.pivotaltracker.com/story/show/166218729) 
- update bugsnag configurations
[Maintains #166218729]

#166218729 update bugsnag configurations

---

app/blueprints/meal_item_blueprint.py
app/controllers/meal_item_controller.py
app/models/base_model.py
app/utils/security.py
tests/integration/endpoints/test_meal_items_endpoints.py
tests/unit/controllers/test_meal_item_controller.py

-  Fix raising of errors when they occur during saving to the database.
- Raise errors when they occur during saving
- Pull and checkout to this branch locally by running `git fetch origin bg-fix-save-method-166112845 && git checkout bg-fix-save-method-166112845`
- Run   `pytest`
- Currently, If saving to the database fails, the save method doesn't give the right log to bugsnag
- [#166112845](https://www.pivotaltracker.com/story/show/166112845)

#166112845 Update save method

---

app/blueprints/user_blueprint.py
app/controllers/user_controller.py
factories/user_factory.py
tests/integration/endpoints/test_role_endpoints.py
tests/integration/endpoints/test_user_endpoints.py
tests/unit/controllers/test_user_controller.py

* fix user endpoints
* fix user endpoints
* Pull and checkout to this branch locally by running `git fetch origin bg-fix-user-endpoints-166177823 && bg-fix-user-endpoints-166177823`
* N/A
* [166177823](https://www.pivotaltracker.com/story/show/166177823)

#166177823 fix user endpoints

---

app/__init__.py
app/blueprints/menu_blueprint.py
app/blueprints/vendor_rating_blueprint.py
app/utils/date_url_validator.py
tests/integration/endpoints/test_menu_endpoints.py

- Add date validation to url params 
- Add date validation to url params 
- Pull and checkout to this branch locally by running `git fetch origin bg-validate-date-166322329 && git checkout bg-validate-date-166322329`
- Run   `pytest`
- [#166322329](https://www.pivotaltracker.com/story/show/166322329)

#166322329 Add date url parameter validation 

---

app/utils/seeders/seed_data.py

* Updates seed data
*Adds newly added roles and user_role model fields to the seed data
* Pull and checkout to this branch locally by running `git fetch origin ch-update-seed-data-166271315`
* Then `git checkout ch-update-seed-data-166271315`
* Start  the virtual environment `. venv/bin/activate`
* Seed the database `flask seed_database`
* N/A
* [166271315](https://www.pivotaltracker.com/story/show/166271315)

#166271315 Update seed data to include newly added fields

---

Dockerfile
Procfile
app/blueprints/documentation/daily_taps.yml
app/blueprints/reports_blueprint.py
app/controllers/reports_controller.py
app/repositories/__init__.py
factories/__init__.py
tests/integration/endpoints/test_orders_endpoints.py
tests/integration/endpoints/test_reports_endpoint.py

* Returns the daily reports of tapped users
* Add an endpoint to return daily tapped users
* add documentation and tests for the task
* Pull and checkout to this branch locally by running `git fetch origin 158378084-admin-see-tapped-users1` && git checkout `158378084-admin-see-tapped-users1`
* Test out the endpoint as per the documentation
[#158378084](https://www.pivotaltracker.com/story/show/158378084)

#158378084 Admin sees tapped users

---

app/models/__init__.py

* Add MealSession logging
* Add MealSession logging
* Pull and checkout to this branch locally by running `git fetch origin ft-meal-session-logging-165184662 && ft-meal-session-logging-165184662`
* N/A
* [165184662](https://www.pivotaltracker.com/story/show/165184662)

#165184662 MealSession logging

---

app/blueprints/documentation/get_vendor_ratings.yml
app/blueprints/vendor_rating_blueprint.py
app/controllers/vendor_rating_controller.py
app/utils/security.py
tests/unit/controllers/test_vendor_rating_controller.py
tests/unit/utils/test_security.py

* Implement query parsing on ratings endpoint
* Implement query parsing on ratings endpoint
* Pull and checkout to this branch locally by running `git fetch origin ch-query-parsers-ratings-166280295 && ch-query-parsers-ratings-166280295`
* start the server `flask run`
* Hit the endpoint `GET {{base-url}}/api/v1/ratings/{{menu_date}}`, it should support query parsing e.g `{{base-url}}/api/v1/ratings/2019-04-23?userId=-LMc4AGZpzFoM_VRopuN`
* N/A
* [166280295](https://www.pivotaltracker.com/story/show/166280295 …

#166280295 implement query parsing on ratings endpoint

---

app/controllers/user_controller.py
tests/integration/endpoints/test_user_endpoints.py

* fix user endpoint responses
* fix user endpoint responses
* Pull and checkout to this branch locally by running `git fetch origin ch-fix-user-endpoints-166492668 && ch-fix-user-endpoints-166492668`
* N/A
* [166492668](https://www.pivotaltracker.com/story/show/166492668)

 #166492668 fix user endpoint responses

---

app.json

- Enable review apps on Heroku
- Enable review apps on Heroku
- Whenever a PR is raised, a Heroku app is made 
* [166499961](https://www.pivotaltracker.com/story/show/166499961)

#166499961 Enable review apps

---

.gitignore
app/utils/cache.py
tests/unit/utils/test_cache.py

* setup REDIS_URL env variable
* setup redis to use a single `REDIS_URL` env variable
* Pull and checkout to this branch locally by running `git fetch origin ch-set-redis-url-166498331 && ch-set-redis-url-166498331`
* N/A
* [166498331](https://www.pivotaltracker.com/story/show/166498331)

#166498331 setup REDIS_URL env variable

---

app/blueprints/documentation/get_order_by_user_id_date_range.yml
app/blueprints/documentation/get_orders_by_date.yml
app/blueprints/documentation/get_orders_by_date_range.yml
app/blueprints/order_blueprint.py

- Add date validation to orders params 
- Add date validation to orders params 
- Update documentation
- Pull and checkout to this branch locally by running `git fetch origin bg-fix-date-validation-on-orders-166540370 && git checkout bg-fix-date-validation-on-orders-166540370`
- Run   `pytest`
- [#166540370](https://www.pivotaltracker.com/story/show/166540370)

#166540370 Add orders date validation

---

app.json
app/utils/seeders/seed_database.py
app/utils/seeders/test_data.py
run.py
tests/unit/utils/test_seeders.py

- add review app test data config
- add review app test data config
- Whenever a PR is raised, a Heroku app is made 
- [#166604276](https://www.pivotaltracker.com/story/show/166604276)

#166604276 Enable review test data

---

app/controllers/order_controller.py

* Fix get orders endpoint to return yesterday's, today's and tomorrow's orders
* Fix get orders endpoint to return yesterday's, today's and tomorrow's orders
* Pull and checkout to this branch locally by running `git fetch origin fix-get-orders &&  fix-get-orders`
* N/A
* N/A

fix get orders endpoint

---

app/blueprints/documentation/create_about.yml
app/blueprints/documentation/create_faq.yml
app/blueprints/documentation/create_location.yml
app/blueprints/documentation/create_meal_session.yml
app/blueprints/documentation/create_menu.yml
app/blueprints/documentation/create_single_meal_item.yml
app/blueprints/documentation/delete_faq.yml
app/blueprints/documentation/delete_location.yml
app/blueprints/documentation/delete_meal_session.yml
app/blueprints/documentation/delete_menu.yml
app/blueprints/documentation/delete_single_meal_item.yml
app/blueprints/documentation/get_about_page.yml
app/blueprints/documentation/get_activities_by_date.yml
app/blueprints/documentation/get_activities_by_date_and_action_type.yml
app/blueprints/documentation/get_admin_menu_period_date_range.yml
app/blueprints/documentation/get_all_locations.yml
app/blueprints/documentation/get_all_meal_items.yml
app/blueprints/documentation/get_faqs.yml
app/blueprints/documentation/get_meal_sessions.yml
app/blueprints/documentation/get_menu_period_date_range.yml
app/blueprints/documentation/get_menu_period_single_date.yml
app/blueprints/documentation/get_single_location.yml
app/blueprints/documentation/get_single_meal_item.yml
app/blueprints/documentation/update_faq.yml
app/blueprints/documentation/update_location.yml
app/blueprints/documentation/update_meal_session.yml
app/blueprints/documentation/update_menu.yml
app/blueprints/documentation/update_single_meal_item.yml
app/blueprints/meal_session_blueprint.py
app/utils/security.py

* update swagger documentation
* update swagger documentation
* Pull and checkout to this branch locally by running `git fetch origin ch-update-swagger-docs-166869465 && ch-update-swagger-docs-166869465`
* N/A
* [166869465](https://www.pivotaltracker.com/story/show/166869465)

#166869465 update swagger documentation 166869465

---

app/controllers/vendor_engagement_controller.py
app/repositories/vendor_engagement_repo.py
tests/unit/repositories/test_vendor_engagement_repo.py

* fix vendor engagement creation to check for existing engagements within a given period of time.
* fix vendor engagement creation to check for existing engagements within a given period of time.
* Pull and checkout to this branch locally by running `git fetch origin bg-fix-engagement-creation-167013102 && bg-fix-engagement-creation-167013102`
* N/A
* [167013102](https://www.pivotaltracker.com/story/show/167013102)

#167013102 fix vendor engagement creation

---

app/controllers/user_controller.py

* add user_role_id to get all admin users' response.
* add user_role_id to get all admin users' response.
* Pull and checkout to this branch locally by running `git fetch origin ch-add-user-role-id-167060140 && ch-add-user-role-id-167060140`
* N/A
* [167060140](https://www.pivotaltracker.com/story/show/167060140)

#167060140 add user_role_id

---

app/controllers/meal_item_controller.py
app/models/__init__.py
app/repositories/base_repo.py
tests/unit/controllers/test_meal_item_controller.py

* update query params to support sql LIKE syntax
* update query params to support sql LIKE syntax
* Pull and checkout to this branch locally by running `git fetch origin ch-update-query-filter-167162574 && ch-update-query-filter-167162574`
* N/A
* [167162574](https://www.pivotaltracker.com/story/show/167162574)

#167162574 update query params to support sql LIKE syntax

---

.gitignore
app/blueprints/documentation/get_menu_template.yml
app/blueprints/documentation/menu_template.yml
app/blueprints/documentation/update_menu_template.yml
app/blueprints/menu_template_blueprint.py
app/controllers/menu_template_controller.py
app/utils/error_handlers.py
app/utils/security.py
tests/integration/endpoints/test_menu_templates.py
tests/unit/utils/test_security.py

- Add endpoint to get a single a menu template
-  add an endpoint to get  a single menu template
- Pull and checkout to this branch locally by running `ft-get-menu-template-166788945 && git checkout ft-get-menu-template-166788945`
- Run the server and go to the URL `http://localhost:5000/api/v1/menu_templates/<id>` to get a menu template 
- Run test `pytest -k pytest -k TestMenuTemplate`
- N/A
- [#166788945](https://www.pivotaltracker.com/story/show/166788945)

#166788945 Endpoint to get single menu template

---

app/utils/slackhelper.py
requirements.in
requirements.txt
tests/unit/utils/test_slack_helper.py

- upgrade slackclient to version 2.0

slackclient 2.0 upgrade

---

app/controllers/base_controller.py
app/controllers/order_controller.py
app/repositories/order_repo.py
tests/unit/controllers/test_order_controller.py

- add query params for orders list endpoints

Fix pagination for orders

---

app/blueprints/documentation/delete_menu_template.yml
app/blueprints/documentation/get_menu_template.yml
app/blueprints/documentation/menu_template.yml
app/blueprints/menu_template_blueprint.py
app/controllers/base_controller.py
app/controllers/menu_template_controller.py
app/models/menu_template.py
app/utils/location_time.py
tests/integration/endpoints/test_menu_templates.py
tests/unit/utils/test_utils.py

- Add endpoint to delete a single a menu template
-  add an endpoint to delete  a single menu template
- Pull and checkout to this branch locally by running `ft-delete-menu-template-#166788856 && git checkout ft-delete-menu-template-#1667888565`
- Run the server and go to the URL `http://localhost:5000/api/v1/menu_templates/<id>` to delete a menu template 
- Run test `pytest -k pytest -k TestMenuTemplate`
- N/A
- [#166788856](https://www.pivotaltracker.com/story/show/166788856)

 #166788856 Endpoint to delete menu a template

---

app/blueprints/documentation/delete_menu_template_item.yml
app/blueprints/menu_template_item_blueprint.py
app/controllers/menu_template_item_controller.py
tests/integration/endpoints/test_menu_template_items.py

- Add endpoint to delete a single a menu template item
-  add an endpoint to delete  a single menu template item
- Pull and checkout to this branch locally by running `ft-delete-menu-template-item && git checkout ft-delete-menu-template-item`
- Run the server and go to the URL `http://localhost:5000/api/v1/menu_template_items/<id>` to delete a menu template  item
- Run test `pytest -k pytest -k TestMenuTemplateItem`
- N/A
- [#166789109](https://www.pivotaltracker.com/story/show/166789109)

#166789109 Endpoint to delete menu template item

---

app/blueprints/documentation/delete_menu_template_item.yml
app/blueprints/documentation/get_menu_template_item.yml
app/blueprints/menu_template_item_blueprint.py
app/controllers/base_controller.py
app/controllers/menu_template_item_controller.py
tests/integration/endpoints/test_menu_template_items.py

- Allow the retrieval of a menu template item
-  add a get function to get a menu_template_item
- Pull and checkout to this branch locally by running `git fetch ft-get-single-menu-template-item-166789179 && git checkout ft-get-single-menu-template-item-166789179`
- Run the server and go to the URL `http://127.0.0.1:5000/api/v1/menu_template_items` to get menu template item
- Run test `pytest -k pytest -k TestMenuTemplateItem`
- [#166789179](https://www.pivotaltracker.com/story/show/166789179)

#166789179 Endpoint to get a single menu template item

---

app/factories/slack_response.py

- fix meal sessions list on the slack bot

Fix bot meal sessions

---

app/blueprints/documentation/update_menu_template_item.yml
app/blueprints/menu_template_item_blueprint.py
app/controllers/menu_template_item_controller.py
tests/integration/endpoints/test_menu_template_items.py

- Add endpoint to update a menu template item
- create an update menu template item endpoint
- add tests for endpoint
- Pull and checkout to this branch locally by running `git fetch origin ft-update-menu-template-item-166789067 && git checkout ft-update-menu-template-item-166789067`
- Run the server and go to the URL `http://localhost:5000/api/v1/menu_template_items` to update a menu template with all [PUT] or partial info [PATCH]
```
{
"mainMealId": 1,
"allowedSide": 1,
"allowedProtein": 1,
"dayId": "Monday"
}
```
- Run test `pytest -k pytest -k TestMenuTemplateItem`
- N/A
- [#166789067](https://www.pivotaltracker.com/story/show/166789067)

#166789067 Endpoint to update menut template item

---

app/controllers/menu_template_item_controller.py
app/repositories/menu_template_item_repo.py
app/utils/security.py
tests/integration/endpoints/test_menu_template_items.py
tests/unit/utils/test_security.py

- Adds check for the type of parameters passed into a URL that can return filtered results.
-  add the check in the security.py file
- Adjust existing tests to ensure they pass
- Pull and checkout to this branch locally by running `git fetch` && git checkout `ch-check-query-param-type-168107627`
- Run the server and go to the URL `http://127.0.0.1:5000/api/v1/menu_template_items?day_id=<id>` and pass in an invalid id.
- Run tests `pytest -k pytest -k test_security`
- N/A
- [#168107627](https://www.pivotaltracker.com/story/show/168107627)

#168107627 Add check for type of params passed into url

---

app/blueprints/documentation/copy_menu_template.yml
app/blueprints/menu_template_blueprint.py
app/blueprints/menu_template_item_blueprint.py
app/controllers/base_controller.py
app/controllers/menu_controller.py
app/controllers/menu_template_controller.py
app/models/base_model.py
app/models/menu_template.py
app/repositories/base_repo.py
app/repositories/menu_template_repo.py
factories/menu_template_item_factory.py
factories/vendor_engagement_factory.py
tests/base_test_utils.py
tests/integration/endpoints/test_menu_template_items.py
tests/integration/endpoints/test_menu_templates.py

- Add endpoint to copy  menu template to menu
- copy menu template to menu 
- add tests for implementations
- Pull and checkout to this branch locally by running `git fetch origin ft-copy-menu-template-into-menus && git checkout ft-copy-menu-template-into-menus`
- Run the server and go to the URL `http://localhost:5000/api/v1/menu_template/copy` to copy template
```
{
"vendorEngagementId": 1,
"startDate": "2019-08-21",
"endDate": "2019-08-23",
"menuTemplateId": 3
}
```
- Run test `pytest -k TestMenuTemplate`
- N/A
- [#166814296](https://www.pivotaltracker.com/story/show/166814296)

#166814296 Copy menu template into menus
