app/blueprints/vendor_blueprint.py, app/controllers/vendor_controller.py, app/utils/auth.py, tests/integration/endpoints/test_vendor_engagement_endpoints.py
- Enable user with admin right to delete a vendor engagement
- Include the endpoint to delete vendor engagement
- Update the blue_print
- With tests for the endpoints
- Clone the branch `ft-admin-delete-engagement`
- Run `pytest` to ensure the tests are passing
- Start the application
- Create samples of vendor-engagement in the database
- Send a `delete` request to the `http://localhost:5000/api/v1/engagement/1` with a role that has `delete_vendor` permission
N/A
￼
N/A
=> Admin to delete vendor engagement

app/blueprints/role_blueprint.py, app/controllers/menu_controller.py, app/controllers/role_controller.py, app/models/base_model.py, tests/integration/endpoints/test_permission_endpoints.py, tests/integration/endpoints/test_role_endpoints.py
add endpoints for managing access rights
- Multiple permissions with the same name
- add get_all_permissions end point
- add update_permission end point
- add delete_permission endpoint
- fix the get_user_roles endpoint
- fix create_user_role avoid duplication
- fix create_user_role avoid non-existing roles
- Write tests for the endpoints
- Clone the branch `ft-user-roles-permission-endpoints`
- Start the application
- with postman test the affected endpoints
N/A
N/A
￼N/A
N/A
=> Create endpoints for managing access rights

app/blueprints/documentation/create_menu.yml, app/blueprints/documentation/update_menu.yml, app/controllers/menu_controller.py
• Enable documentation of urls
**Description of Task  completed?**
• create menu and update menu documentation done
• Clone the branch `fx-menu-post-list-data`  
• Checkout to the branch  
• Run `python run.py runserver`
• browse `http://{server_name}/apidocs`
=> working version of swagger documentation for create & update menu

app/repositories/vendor_engagement_repo.py, tests/unit/repositories/test_vendor_engagement_repo.py
- Create operations for vendor engagement
- User can delete and re-create engagements for a given vendor
- Run python run.py runserver
- Create an engagement for a given vendor
- Delete the newly created engagement
- Try to re-create the deleted engagement. This should be successful
- Previously, re-creating a deleted engagement would fail with a response
```
{ 
"msg": "An engagement already exists for this period. Kindly disable engagement first."
}
```
- [163782820](https://www.pivotaltracker.com/story/show/163782820)
=> #163782820 Fix creating vendor engagement

.circleci/config.yml
- Update Circle CI's `config.yml` file to use `Pytest` instead of `Unitest` for running tests
- Circle CI should use `Pytest` instead of `Unitest` for running tests
- None
- Using Unitest to run tests does not allow some tests aspects to be initiated. This is fixed by using Pytest to run tests instead.
- [163790193](https://www.pivotaltracker.com/story/show/163790193)
=> #163790193 Fix running tests on circle CI

app/controllers/bot_controller.py
- Ensures that beyond 3pm on Sunday, it is not possible to place an order against the next day, using Slack.
-modify the BotController so that the right days are available for meal booking.
- from slack, use the `aetest` command to place order. If you are doing that on Sunday, the next available day will be Tuesday.
None
=> fix available booking day

tests/unit/test_utils.py
- ensure that that for current_time_by_time_zone function passes irrespective of the time of the day.
-the test was earlier written but fails at a certain time window. This fix updates the test to be able to pass at all times.
- run `pytest` at any time between 12 midnight and 4 am to confirm there are no failures
None
=> fix test-current-time-by-time-zone

app/controllers/vendor_engagement_controller.py, app/repositories/base_repo.py, tests/unit/repositories/test_base_repo.py
- Fixes issues with a get request on the endpoint `/api/v1/engagements/` not returning data sorted according to the `start_date`
- Create two instance methods; one to return data for a model in ascending order and the other to return data in descending order.
- Refactor the list_vendor_engagement method of the VendorEngagementController class to extract engagements sorted in descending order of `start_date`
- Write tests for the newly added code.
- Pull this branch locally by running `git fetch bg-fix-engagement-sort-163870674`
- Create a vendor by performing a post on the endpoint `api/v1/vendors/`
- Create two engagements, of different dates, using this vendor by performing a post …
=> #163870674 - Fix sorting vendor engagements

tests/unit/controllers/test_base_controller.py
- Increases test coverage of the base_controller.py file to 100%
- Write tests to cover lines `10, 20, 23-26, 29-32, 52, 55 and 62` of the `base_controller.py` file
- Pull this branch locally by running `git fetch ch-increase-base-controller-coverage-163938942`
- Run the command `pytest --cov=app/` to get the coverage for the app
- Run the command `coveralls html` to generate a html coverage report
- Navigate to `andelaeatsapi/htmlcov/index.html` and view the coverage of base_controller.py file
- The coverage should be at 100%
- Previously the test coverage of the `base_controller.py` file was at about 70% …
=> #163938942 - Increase Base controller test coverage

app/controllers/bot_controller.py, tests/integration/endpoints/test_bot_endpoints.py
- ensures that booking via slack has a cut off of 3 pm
- fix the function that handles the checking
- add test to check it
- run `pytest`
None
=> fix slack booking cut off time

tests/unit/utils/test_slack_helper.py
- Increases test coverage of the `slackhelper.py` file located in `app/utils/slackhelper.py`  file to 100%
- Write tests to cover all lines of the `slackhelper.py` file
- Pull this branch locally by running `git fetch ch-increase-slack-helper-test-coverage-163973598`
- Run the command `pytest --cov=app/` to get the coverage for the app
- Run the command `coveralls html` to generate a html coverage report
- Navigate to `andelaeatsapi/htmlcov/index.html` and view the coverage of slackhelper.py file
- The coverage should be at 100%
- Previously the test coverage of the `slackhelper.py` file was at about 69%
**What …
=> #163973598 - Increase slack helper utility test coverage

tests/unit/utils/test_utils.py
- refactor the test on `current_time_by_time_zone` function to use mock dates.
* Change the existing implementation to the one that uses mocked date
* run `pytest tests/unit/test_utils.py` 
* None
=> Refactor test for current_time_by_time_zone

tests/base_test_case.py, tests/unit/services/test_andela_service.py
- Increases test coverage of the `andela.py` file located in `app/services`  file to 100%
- Write tests to cover all lines of the `andela.py` file
- Pull this branch locally by running `git fetch ch-increase-andela-service-test-coverage-163980458`
- Run the command `pytest --cov=app/` to get the coverage for the app
- Run the command `coveralls html` to generate a html coverage report
- Navigate to `andelaeatsapi/htmlcov/index.html` and view the coverage of andela.py file
- The coverage should be at 100%
- Previously the test coverage of the `andela.py` file was not 100%
**What are the relevant pivotal tracker …
=> #163980458- Increase andela service files test coverage

app/controllers/vendor_controller.py, tests/integration/endpoints/test_vendor_endpoints.py
- Fixes issues with a get request on the endpoint `/api/v1/vendors/` not returning data sorted according to the `name`
- Refactor the list_vendors method of the VendorController class to extract engagements sorted in ascending order of `name`
- Write tests for the newly added code.
- Pull this branch locally by running `git fetch bg-sort-vendor-data-in-asc-by-name-164008849`
- Create three vendors, with their names in any order, by performing a post on the endpoint `api/v1/vendors/`
- Perform a get request on the endpoint `api/v1/vendors/` and you should be able to get results sorted according to `vendor names` in ascending order.
- …
=> #164008849 - Fix sort order of returned vendor data

app/controllers/meal_item_controller.py, app/repositories/base_repo.py, tests/integration/endpoints/test_meal_items_endpoints.py, tests/integration/endpoints/test_vendor_engagement_endpoints.py, tests/unit/repositories/test_base_repo.py
- Fixes issues with a get request on the endpoint `/api/v1/meal-items/` not returning data sorted according to the `name`
- Modify `list_meals` method of the `MealItemController`class located in the `meal_item_controller.py` file to return data unpaginated and sorted by `meal_item name`
- Add two methods to the `BaseRepo`; one to get unpaginated data in ascending order and the other to get unpaginated data in descending order.
- Add tests for code just added
- Refactor any other failing tests
- Pull this branch locally by running `git fetch bg-fix-meal-list-data-sort-order-164014105`
- Create three vendors, with their names in any order, by performing a post on the endpoint …
=> #164014105 - Fix sort order of returned meal_item data to ascending by name

tests/integration/endpoints/test_bot_endpoints.py, tests/mock.py
* Increase the test coverage of bot controller and  add 100% coverage for bot blueprint
* Add test for various stages of the slack bot interactions
* 100 % coverage for the bot blueprint
Run the command ` pytest --cov=app.controllers.bot_controller tests/integration/endpoints/test_bot_endpoints.py
` to see the coverage
* None
=> Add more tests to the bot controller and bot blueprint

app/controllers/bot_controller.py, tests/integration/endpoints/test_bot_endpoints.py, tests/mock.py
* Increase the test coverage of bot controller to 99% 
* Add test for various stages of the slack bot interactions
* 99% coverage for the bot controller
Run the command ` pytest --cov=app.controllers.bot_controller tests/integration/endpoints/test_bot_endpoints.py
` to see the coverage
* None
=> Increase test coverage of bot controller to 99%

app/repositories/menu_repo.py
- Fixes issues with a get request on the endpoint `/api/v1/admin/menus/{meal_period}/{start_date}/{end_date}` not returning data sorted in descending order according to the `date` field.
- Modify `get_range_paginated_options` method of the `MenuRepo` class to return data sorted in descending order by `date`
- Pull this branch locally by running `git fetch bg-sort-menus-in-descending-order-164046943`
- Run `Pytest`
- Previously data on `/api/v1/admin/menus/{meal_period}/{start_date}/{end_date}` endpoint was returning data sorted in ascending order according to the `date` field.
- …
=> #164046943 - Modify menu endpoint

.circleci/config.yml, app/utils/auth.py, config/env.py
* update token decoding functionality to include a check for token expiry
* update token decoding functionality to include a check for token expiry
* Add the Andela JWT decode public keys `JWT_PUBLIC_KEY` and `JWT_PUBLIC_KEY_STAGING`
to the `.env` file and try making a request to any endpoint with an expired token. The request should be unsuccessful with the `Token expired` message.
* The token decoding process initially was not checking for token expiry. 
* [64099935](https://www.pivotaltracker.com/story/show/64099935) 
[Maintains #164099935]
=> #164099935 update token decoding functionality to include expired token check

app/blueprints/documentation/create_order_rating.yml, app/controllers/vendor_rating_controller.py, tests/unit/controllers/test_vendor_rating_controller.py
* Add ability to rate previous day manu
* update the meal rating endpoint so user can only rate past meal
* update the endpoint documentation
* fix failing tests
* pull the branch `rate-past-meal` and checkout to the branch
* send  `post` request to `localhost:5000/api/v1/rating/` with the payload:
`{
"rating": 5,
"engagementId": 1 ,
"mainMealId":1 ,
"serviceDate": "2019-02-28" 
}`
If the meal serviceDate is is the previous day, the rating will be successful. If you attempt to rate a menu whose service date is today or in the future, the request will fail
* Users are to be given ability to rate a meal they have eaten even if they did no …
=> Enable rating of menu from previous day

app/controllers/user_controller.py
What does this PR do?
- Fix bug of returning the admin users list duplicating the last admin user entered.
Description of Task to be completed?
- API returned a list of admin users with the last admin user's details duplicated for all the user records to be returned.
How should this be manually tested?
```
pytest --cov=app.controllers.user_controller tests/unit/controllers/test_user_controller.py
```
Any background context you want to provide?
- Invalid admin list returned when querying for admin users.
What are the relevant pivotal tracker stories?
[158456181](https://www.pivotaltracker.com/story/show/158456181)
=> Fixing bug where listing admin users returned an list 

app/models/__init__.py, app/models/listener_helpers.py, tests/unit/models/test_hard_delete_on_model.py
- Add event listeners to the Admin Models
- Add after_insert, after_update and after_delete event listeners to the models: Vendor, 
VendorEngagement, MealItem, Menu, Faq, Role, Permission, UserRole, and Location.
- Add after_update and after_delete event listeners to the VendorRating model
1.  Pull the branch `ch-event-listener-vendor-model` locally to your machine.
2. Start the application by running `python run.py runserver`
3. Using the endpoint for any of the Models specified above, create, update and delete any entity.
4. Using a tool such as `pgAdmin` or `postico` open up the table `activities` and you should see a log of any Activity you performed. An illustration of what you …
=> #164240383 Log activities that change state of the database 

app/blueprints/activity_blueprint.py, app/blueprints/base_blueprint.py, app/blueprints/documentation/get_activities_by_date.yml, app/blueprints/documentation/get_activities_by_date_and_action_type.yml, app/controllers/activity_controller.py, app/controllers/base_controller.py, app/utils/security.py, factories/activity_factory.py, tests/integration/endpoints/test_activity_endpoints.py, tests/unit/utils/test_security.py
- Adds endpoints that enable the viewing of activity logs
- Create endpoint `api/v1/activities/range` that enables the viewing of all activities between certain two dates by specifying a query parameter `date_range=2019-01-30:2019-02-30`
- Create endpoint `api/v1/activities/action_range` that enables the viewing of all activities between certain two dates by specifying two query parameters. An example form is `date_range=2019-01-30:2019-02-30&action_type=create`
- Add documentation for the endpoints
- Pull the branch `ch-add-activity-blueprint-and-controllers-164240383` and checkout to it.
- Try to create a couple of vendors
- Try to access the endpoints above by specifying the date …
=> Add endpoints to view activity logs

app/blueprints/documentation/get_all_admin_users.yml, app/controllers/user_controller.py
* add `Roles` property to the result of fetching all admin users
* refactor the controller to add `Roles` property
* update the endpoint documentation
* fix failing tests
* pull the branch `update-fetch-admin-users` and checkout to the branch
* send a get request to `http://localhost:5000/api/v1/users/admin`. If you have the appropriate permission, you will receive a success response, showing the admin users. For each user, a list of their roles is also attached.
[Update [GET]users/admin endpoint](https://www.pivotaltracker.com/story/show/164490677)
**Sample screenshot**
=> Add 'Roles' property to the result of fetching admin users

app/blueprints/documentation/get_report.yml, app/controllers/reports_controller.py, tests/integration/endpoints/test_reports_endpoint.py
* Creates the endpoint for dashboard report
* add the endpoint that returns the rating and order information for a given period
* Add documentation for the endpoint
* pull the branch `all-vendors-report` and checkout to the branch
* send  `get` request to `localhost:5000/api/v1/reports/` 
You will get the report for the past 14 days, by default. To customize the number of days, add the `?start_date=x&`?`end_date=y` to the url, where`x`  and `y` are dates in format`YYYY-MM-dd`. You can also add the query parameter `all_vendors_comparison=true` to get the report for all vendors for all times
**What are the relevant pivotal tracker …
=> #158863653 Generate summary report for dashboard

app/blueprints/about_blueprint.py, app/blueprints/faq_blueprint.py, app/utils/seeders/seed_data.py, tests/integration/endpoints/test_about_endpoint.py, tests/integration/endpoints/test_faq_enpoints.py
* change the name of the admin role from "Administrator" to "admin"
* protect the create about endpoint
* update tests
* change the name of the admin role from "Administrator" to "admin"
* protect the create about endpoint
* update tests
* Pull and checkout to this branch locally by running `git fetch origin bg-fix-admin-naming-164831637 && git checkout bg-fix-admin-naming-164831637`
* Run tests `pytest --cov=app/`
* The `FAQ` and `About` endpoints must be protected
* N/A.
* [164831637](https://www.pivotaltracker.com/story/show/164831637)
=> #164831637 change the name of the admin role

app/models/vendor.py
What does this PR do?
- Allow nullable average_rating.
Description of Task to be completed?
- Vendor records that already exist should have null values.
How should this be manually tested?
- N/A
Any background context you want to provide?
- Records that already exists for vendors should not be affected by the change.
What are the relevant pivotal tracker stories?
- 164657450
=> Average rating nullable

app/controllers/vendor_rating_controller.py, app/repositories/vendor_repo.py, tests/unit/controllers/test_vendor_rating_controller.py, tests/unit/repositories/test_vendor_repo.py
* Automatically updates vendor average rating
* update the rating creation endpoints to automatically update vendor average rating
* add tests for the affected repo
* add tests for the affected controller
* pull the branch `164890643-vendor-avg-rating` and checkout to the branch
* send  `get` request to `localhost:5000/api/v1/vendors/` The returned vendors have average rating field
N/A
[164890643](https://www.pivotaltracker.com/story/show/164890643)
=> #164890643 Update vendor average rating after every rating

app/blueprints/documentation/delete_user.yml, app/blueprints/user_blueprint.py, app/controllers/user_controller.py, tests/integration/endpoints/test_user_endpoints.py
* Add endpoint to delete user
* add the endpoint to enable authorised user delete a user
* add tests for the affected repo
* add tests for the affected controller
* add PAI documentation for the endpoint
* pull the branch `164945305-add-auto-reminder` and checkout to the branch
* add sample users to the database
* send  `delete` request to `localhost:5000/api/v1/users/{id}. 
N/A
[164679874](https://www.pivotaltracker.com/story/show/164679874)
=> #1646799874 Add endpoint to delete user

.circleci/config.yml, app/controllers/bot_controller.py
* Removes the breakfast option from the slack bot
* Comment out the code block responsible for displaying the breakfast option.
* Pull and checkout to this branch locally by running `git fetch origin ch-remove-breakfast-option-in-slack-bot-165528676 && git checkout ch-remove-breakfast-option-in-slack-bot-165528676`
* Download ngrok and configure the IP address it generates on your machine to be used with slack.(You may need to ask the TTL for access to the slack web interface to make the changes)
* Start the /testandelaeats application on slack and try to follow the prompts. You should not be able to see the breakfast option
N/A
**What …
=> #165528676 Remove breakfast option completely from slack bot

app.json, app/blueprints/documentation/create_user.yml, app/blueprints/documentation/get_all_meal_items.yml, app/blueprints/documentation/update_user.yml, app/blueprints/meal_item_blueprint.py, app/controllers/meal_item_controller.py, tests/unit/controllers/test_meal_item_controller.py
* Implement query parsing on ratings endpoint
* add query parser to meal-item endpoint
* Pull and checkout to this branch locally by running `git fetch origin ch-query-parser-meal-items-166577810 && ch-query-parser-meal-items-166577810`
* start the server `flask run`
* Hit the endpoint `GET {{base-url}}/api/v1/meal-items`, it should support query parsing e.g `{{base-url}}/api/v1/meal-items?name=testname`
* N/A
* [166577810](https://www.pivotaltracker.com/story/show/166577810)
=> #166577810 implement query parsing on ratings endpoint

app/controllers/role_controller.py, app/controllers/user_controller.py, tests/unit/controllers/test_user_controller.py
* fix get admin user endpoint to return pagination meta data
* fix get admin user endpoint to return pagination meta data
* fix create user-role endpoint to return user name
* Pull and checkout to this branch locally by running `git fetch origin bg-fix-get-admin-userendpoint-166755081 && bg-fix-get-admin-userendpoint-166755081`
* N/A
* [166755081](https://www.pivotaltracker.com/story/show/166755081)
=> Bg fix get admin userendpoint 166755081

app/controllers/order_controller.py, tests/unit/controllers/test_order_controller.py
* Handles scenario for when user attempts to collect an order for which the order date has passed
* User should not be able to collect an order with passed order date
* Pull and checkout to this branch locally by running `git fetch origin bg-collect-order-valid-date-167034941 && git checkout bg-collect-order-valid-date-167034941`
* Start  the virtual environment `. venv/bin/activate`
* run server `flask run`
* Create an order in your local db ad give it a past order date
* In postman, hit the collect enpoint  `POST {{base-url}}/orders/collect`, with request data corresponding to the order created above
* The following response will be returned
```
{
"msg": "Cannot collect order for …
```
=> #167034941 Order can be collected after the order date has passed.

app/blueprints/documentation/get_menu_template_items.yml, app/blueprints/menu_template_item_blueprint.py, app/controllers/menu_template_item_controller.py, app/repositories/menu_template_item_repo.py, tests/integration/endpoints/test_menu_template_items.py
- Allow the retrieval of menu template items for a particular template and day
-  add a get function to retrieve menu_template_items for specific template and day
- Pull and checkout to this branch locally by running `git fetch` && `git checkout ft-get-menutemplate-items-166788919`
- Run the server and go to the URL `http://127.0.0.1:5000/api/v1/menu_template_items?template_id=<id>&day_id=<id>` to get menu template items for particular template and day
- Run test `pytest -k pytest -k TestMenuTemplateItem`
- N/A
- [#166788919](https://www.pivotaltracker.com/story/show/166788919)
=> #166788919 Get menu template items

app/blueprints/menu_template_blueprint.py, tests/integration/endpoints/test_menu_templates.py
- add length validation on menu templates
-  add length validation on menu templates
- Pull and checkout to this branch locally by running `git fetch add-length-validation-168335901 && add-length-validation-168335901`
- Run test `pytest -k pytest -k test_create_menu_template_with_name_greater_than_50_fails`
- [#168335901](https://www.pivotaltracker.com/story/show/168335901)
=> #168335901 Add name length validation on menu template
